#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinApis.Droid.Resource", IsApplication=true)]

namespace XamarinApis.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int favorite = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int notfavorite = 2130837505;
			
			// aapt resource value: 0x7F07004E
			public const int abc_tab_indicator_mtrl_alpha = 2131165262;
			
			// aapt resource value: 0x7F070056
			public const int abc_textfield_activated_mtrl_alpha = 2131165270;
			
			// aapt resource value: 0x7F070057
			public const int abc_textfield_default_mtrl_alpha = 2131165271;
			
			// aapt resource value: 0x7F070058
			public const int abc_textfield_search_activated_mtrl_alpha = 2131165272;
			
			// aapt resource value: 0x7F070059
			public const int abc_textfield_search_default_mtrl_alpha = 2131165273;
			
			// aapt resource value: 0x7F07005A
			public const int abc_textfield_search_material = 2131165274;
			
			// aapt resource value: 0x7F07004F
			public const int abc_text_cursor_material = 2131165263;
			
			// aapt resource value: 0x7F070050
			public const int abc_text_select_handle_left_mtrl_dark = 2131165264;
			
			// aapt resource value: 0x7F070051
			public const int abc_text_select_handle_left_mtrl_light = 2131165265;
			
			// aapt resource value: 0x7F070052
			public const int abc_text_select_handle_middle_mtrl_dark = 2131165266;
			
			// aapt resource value: 0x7F070053
			public const int abc_text_select_handle_middle_mtrl_light = 2131165267;
			
			// aapt resource value: 0x7F070054
			public const int abc_text_select_handle_right_mtrl_dark = 2131165268;
			
			// aapt resource value: 0x7F070055
			public const int abc_text_select_handle_right_mtrl_light = 2131165269;
			
			// aapt resource value: 0x7F07005B
			public const int abc_vector_test = 2131165275;
			
			// aapt resource value: 0x7F07005C
			public const int avd_hide_password = 2131165276;
			
			// aapt resource value: 0x7F07005D
			public const int avd_show_password = 2131165277;
			
			// aapt resource value: 0x7F07005E
			public const int btn_checkbox_checked_mtrl = 2131165278;
			
			// aapt resource value: 0x7F07005F
			public const int btn_checkbox_checked_to_unchecked_mtrl_animation = 2131165279;
			
			// aapt resource value: 0x7F070060
			public const int btn_checkbox_unchecked_mtrl = 2131165280;
			
			// aapt resource value: 0x7F070061
			public const int btn_checkbox_unchecked_to_checked_mtrl_animation = 2131165281;
			
			// aapt resource value: 0x7F070062
			public const int btn_radio_off_mtrl = 2131165282;
			
			// aapt resource value: 0x7F070063
			public const int btn_radio_off_to_on_mtrl_animation = 2131165283;
			
			// aapt resource value: 0x7F070064
			public const int btn_radio_on_mtrl = 2131165284;
			
			// aapt resource value: 0x7F070065
			public const int btn_radio_on_to_off_mtrl_animation = 2131165285;
			
			// aapt resource value: 0x7F070066
			public const int design_bottom_navigation_item_background = 2131165286;
			
			// aapt resource value: 0x7F070067
			public const int design_fab_background = 2131165287;
			
			// aapt resource value: 0x7F070068
			public const int design_ic_visibility = 2131165288;
			
			// aapt resource value: 0x7F070069
			public const int design_ic_visibility_off = 2131165289;
			
			// aapt resource value: 0x7F07006A
			public const int design_password_eye = 2131165290;
			
			// aapt resource value: 0x7F07006B
			public const int design_snackbar_background = 2131165291;
			
			// aapt resource value: 0x7F07006C
			public const int favorite = 2131165292;
			
			// aapt resource value: 0x7F07006D
			public const int ic_mtrl_checked_circle = 2131165293;
			
			// aapt resource value: 0x7F07006E
			public const int ic_mtrl_chip_checked_black = 2131165294;
			
			// aapt resource value: 0x7F07006F
			public const int ic_mtrl_chip_checked_circle = 2131165295;
			
			// aapt resource value: 0x7F070070
			public const int ic_mtrl_chip_close_circle = 2131165296;
			
			// aapt resource value: 0x7F070071
			public const int material_ic_calendar_black_24dp = 2131165297;
			
			// aapt resource value: 0x7F070072
			public const int material_ic_clear_black_24dp = 2131165298;
			
			// aapt resource value: 0x7F070073
			public const int material_ic_edit_black_24dp = 2131165299;
			
			// aapt resource value: 0x7F070074
			public const int material_ic_keyboard_arrow_left_black_24dp = 2131165300;
			
			// aapt resource value: 0x7F070075
			public const int material_ic_keyboard_arrow_right_black_24dp = 2131165301;
			
			// aapt resource value: 0x7F070076
			public const int material_ic_menu_arrow_down_black_24dp = 2131165302;
			
			// aapt resource value: 0x7F070077
			public const int material_ic_menu_arrow_up_black_24dp = 2131165303;
			
			// aapt resource value: 0x7F070078
			public const int mtrl_dialog_background = 2131165304;
			
			// aapt resource value: 0x7F070079
			public const int mtrl_dropdown_arrow = 2131165305;
			
			// aapt resource value: 0x7F07007A
			public const int mtrl_ic_arrow_drop_down = 2131165306;
			
			// aapt resource value: 0x7F07007B
			public const int mtrl_ic_arrow_drop_up = 2131165307;
			
			// aapt resource value: 0x7F07007C
			public const int mtrl_ic_cancel = 2131165308;
			
			// aapt resource value: 0x7F07007D
			public const int mtrl_ic_error = 2131165309;
			
			// aapt resource value: 0x7F07007E
			public const int mtrl_popupmenu_background = 2131165310;
			
			// aapt resource value: 0x7F07007F
			public const int mtrl_popupmenu_background_dark = 2131165311;
			
			// aapt resource value: 0x7F070080
			public const int mtrl_tabs_default_indicator = 2131165312;
			
			// aapt resource value: 0x7F070081
			public const int navigation_empty_icon = 2131165313;
			
			// aapt resource value: 0x7F070082
			public const int notfavorite = 2131165314;
			
			// aapt resource value: 0x7F070083
			public const int notification_action_background = 2131165315;
			
			// aapt resource value: 0x7F070084
			public const int notification_bg = 2131165316;
			
			// aapt resource value: 0x7F070085
			public const int notification_bg_low = 2131165317;
			
			// aapt resource value: 0x7F070086
			public const int notification_bg_low_normal = 2131165318;
			
			// aapt resource value: 0x7F070087
			public const int notification_bg_low_pressed = 2131165319;
			
			// aapt resource value: 0x7F070088
			public const int notification_bg_normal = 2131165320;
			
			// aapt resource value: 0x7F070089
			public const int notification_bg_normal_pressed = 2131165321;
			
			// aapt resource value: 0x7F07008A
			public const int notification_icon_background = 2131165322;
			
			// aapt resource value: 0x7F07008B
			public const int notification_template_icon_bg = 2131165323;
			
			// aapt resource value: 0x7F07008C
			public const int notification_template_icon_low_bg = 2131165324;
			
			// aapt resource value: 0x7F07008D
			public const int notification_tile_bg = 2131165325;
			
			// aapt resource value: 0x7F07008E
			public const int notify_panel_notification_icon_bg = 2131165326;
			
			// aapt resource value: 0x7F07008F
			public const int test_custom_background = 2131165327;
			
			// aapt resource value: 0x7F070090
			public const int tooltip_frame_dark = 2131165328;
			
			// aapt resource value: 0x7F070091
			public const int tooltip_frame_light = 2131165329;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
